/**
 * @fileOverview Stripe Connect Service — Seller Onboarding + Payouts
 *
 * P0 FIX (war room): the audit identified that NO Stripe Connect onboarding
 * flow existed in the codebase. The `stripe_account_id` column on `profiles`
 * was only ever populated by the seed service with fake `acct_TEST_<random>`
 * IDs. In production, no real seller could ever complete Stripe Connect
 * onboarding — they had no way to start the flow, no way to receive
 * onboarding links, and no way to track their account status.
 *
 * This module implements the real Stripe Connect onboarding flow:
 *
 *   1. `createConnectAccount()` — creates a Stripe Connect account for a
 *      seller (type='express', which is the recommended type for
 *      marketplaces — Stripe handles the KYC UI).
 *   2. `createAccountLink()` — generates an onboarding URL the seller
 *      visits to complete their Stripe Connect setup.
 *   3. `getAccountStatus()` — checks the seller's Connect account status
 *      (charges_enabled, payouts_enabled, requirements).
 *   4. `handleAccountUpdated()` — webhook handler for `account.updated`
 *      events (syncs account status back to the DB).
 *
 * VERIFICATION STATUS:
 *   - CODE-VERIFIED: TypeScript compiles, types are correct, all code paths
 *     are covered. The flow uses the recommended Stripe Express Connect
 *     pattern documented at https://stripe.com/docs/connect/express-accounts.
 *   - LIVE-VERIFIED: REQUIRES:
 *     1. Real STRIPE_SECRET_KEY with Connect enabled (not all Stripe
 *        accounts have Connect — it requires Stripe approval).
 *     2. Stripe CLI (`stripe listen --forward-to localhost:9002/api/webhooks/stripe`)
 *        to test webhook delivery locally.
 *     3. Real seller email addresses to test the onboarding flow end-to-end.
 *     4. The Stripe Connect account must be activated (charges_enabled=true)
 *        before live payouts can occur.
 *
 *   Until those are in place, calling these functions will fail at runtime
 *   with a Stripe API error. They do NOT silently no-op or return fake data.
 */

import Stripe from 'stripe';
import { requireEnv } from '@/lib/env';
import { getSupabaseAdmin } from '@/lib/supabase-admin';
import { PaymentLogger, PaymentError, PaymentErrorCode } from '@/lib/payment/errors';
import { getErrorMessage } from '@/types';

// ============================================================
// STRIPE CLIENT (singleton)
// ============================================================

let _stripe: Stripe | null = null;

function getStripe(): Stripe {
  if (!_stripe) {
    _stripe = new Stripe(requireEnv('STRIPE_SECRET_KEY'), {
      apiVersion: '2024-06-20',
    });
  }
  return _stripe;
}

// ============================================================
// TYPES
// ============================================================

export interface ConnectAccountStatus {
  stripeAccountId: string | null;
  stripeConnected: boolean;
  chargesEnabled: boolean;
  payoutsEnabled: boolean;
  detailsSubmitted: boolean;
  requirements: {
    currentlyDue: string[];
    eventuallyDue: string[];
    pastDue: string[];
    disabledReason: string | null;
  };
}

export interface CreateAccountLinkResult {
  url: string;
  expiresAt: Date;
}

// ============================================================
// CONNECT ACCOUNT CREATION
// ============================================================

/**
 * Create a Stripe Connect Express account for a seller.
 *
 * This is the first step in the onboarding flow. The seller must then
 * visit the onboarding URL (generated by `createAccountLink()`) to
 * complete their account setup (provide business details, bank account, etc.).
 *
 * Idempotency: if the seller already has a `stripe_account_id` in their
 * profile, this function does NOT create a new account — it returns the
 * existing account ID. This prevents duplicate accounts from being created
 * if the seller clicks "Connect Stripe" multiple times.
 *
 * @param sellerId - the seller's user ID (auth.uid())
 * @param sellerEmail - the seller's email address (used as Stripe account email)
 * @param sellerName - the seller's full name or store name
 * @returns the Stripe Connect account ID
 */
export async function createConnectAccount(
  sellerId: string,
  sellerEmail: string,
  sellerName: string
): Promise<string> {
  const traceId = `connect_create_${sellerId}_${Date.now()}`;
  const stripe = getStripe();
  const admin = getSupabaseAdmin();

  PaymentLogger.info(traceId, 'connect_account_create_started', `Creating Stripe Connect account for seller ${sellerId}`, {
    sellerId,
    sellerEmail,
  });

  // Check if the seller already has a stripe_account_id (idempotency)
  const { data: profile, error: profileError } = await (admin
    .from('profiles') as any)
    .select('stripe_account_id, stripe_connected')
    .eq('id', sellerId)
    .single();

  if (profileError || !profile) {
    throw new PaymentError(PaymentErrorCode.DATABASE_RPC_FAILED, {
      message: `Failed to fetch seller profile: ${profileError?.message ?? 'profile not found'}`,
      traceId,
      context: { sellerId },
    });
  }

  if (profile.stripe_account_id && !profile.stripe_account_id.startsWith('acct_TEST_')) {
    // Seller already has a real Stripe Connect account — return it.
    // (TEST_-prefixed accounts are from seed data and should be replaced.)
    PaymentLogger.info(traceId, 'connect_account_exists', `Seller ${sellerId} already has Stripe account ${profile.stripe_account_id}`, {
      sellerId,
      stripeAccountId: profile.stripe_account_id,
    });
    return profile.stripe_account_id;
  }

  // Create the Stripe Connect Express account
  // Type: 'express' — Stripe handles the KYC UI, recommended for marketplaces
  // See: https://stripe.com/docs/connect/express-accounts
  const account = await stripe.accounts.create({
    type: 'express',
    email: sellerEmail,
    metadata: {
      sellerId,
      sellerName,
      platform: 'vendortrack',
      createdAt: new Date().toISOString(),
    },
  }, {
    // Idempotency key: deterministic per seller. If the seller clicks
    // "Connect Stripe" twice rapidly, the second call returns the original
    // account instead of creating a duplicate.
    idempotencyKey: `connect_account:${sellerId}`,
  });

  // Persist the stripe_account_id to the seller's profile
  const { error: updateError } = await (admin
    .from('profiles') as any)
    .update({
      stripe_account_id: account.id,
      stripe_connected: false, // Not fully connected until onboarding is complete
    })
    .eq('id', sellerId);

  if (updateError) {
    // Critical: if we can't persist the account ID, the seller will not be
    // able to receive payouts. Log CRITICAL and throw.
    PaymentLogger.critical(traceId, 'connect_account_persist_failed', `Stripe account ${account.id} created but failed to persist to profile: ${updateError.message}`, {
      sellerId,
      stripeAccountId: account.id,
      error: updateError.message,
    });
    throw new PaymentError(PaymentErrorCode.DATABASE_TRANSACTION_FAILED, {
      message: `Stripe account created (${account.id}) but failed to persist to seller profile. Manual intervention required.`,
      traceId,
      context: { sellerId, stripeAccountId: account.id, dbError: updateError.message },
    });
  }

  PaymentLogger.info(traceId, 'connect_account_created', `Stripe Connect account ${account.id} created for seller ${sellerId}`, {
    sellerId,
    stripeAccountId: account.id,
  });

  return account.id;
}

// ============================================================
// ACCOUNT LINK (ONBOARDING URL)
// ============================================================

/**
 * Generate an onboarding URL for the seller to complete their Stripe Connect setup.
 *
 * The seller visits this URL in their browser, where Stripe collects:
 *   - Business details (name, address, tax ID)
 *   - Bank account information (for payouts)
 *   - Identity verification documents
 *
 * After completing onboarding, Stripe redirects to `returnUrl` with
 * the seller back on the platform.
 *
 * If the seller refreshes the onboarding page or visits it again,
 * Stripe may have expired the previous account link — this function
 * should be called again to generate a fresh URL.
 *
 * @param stripeAccountId - the seller's Stripe Connect account ID
 * @param sellerId - the seller's user ID (for traceability)
 * @returns the onboarding URL + expiry time
 */
export async function createAccountLink(
  stripeAccountId: string,
  sellerId: string
): Promise<CreateAccountLinkResult> {
  const traceId = `connect_link_${sellerId}_${Date.now()}`;
  const stripe = getStripe();

  PaymentLogger.info(traceId, 'connect_link_create_started', `Generating onboarding URL for account ${stripeAccountId}`, {
    sellerId,
    stripeAccountId,
  });

  // The return URL is where Stripe sends the seller after onboarding completes.
  // We use the VERCEL_URL env var (set automatically by Vercel) or fall back
  // to localhost for development.
  const baseUrl = process.env.VERCEL_URL
    ? `https://${process.env.VERCEL_URL}`
    : process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:9002';

  const returnUrl = `${baseUrl}/seller-dashboard/settings?stripe_onboarding=complete`;
  const refreshUrl = `${baseUrl}/seller-dashboard/settings?stripe_onboarding=refresh`;

  const accountLink = await stripe.accountLinks.create({
    account: stripeAccountId,
    refresh_url: refreshUrl,
    return_url: returnUrl,
    type: 'account_onboarding',
  }, {
    // Idempotency key: include a timestamp so each request generates a
    // fresh link (account links expire after 48 hours per Stripe docs).
    // We do NOT want to dedupe here — every onboarding click should
    // produce a fresh link in case the previous one expired.
    idempotencyKey: `connect_link:${stripeAccountId}:${Date.now()}`,
  });

  const expiresAt = new Date(accountLink.expires_at * 1000);

  PaymentLogger.info(traceId, 'connect_link_created', `Onboarding URL generated for account ${stripeAccountId} (expires ${expiresAt.toISOString()})`, {
    sellerId,
    stripeAccountId,
    expiresAt: expiresAt.toISOString(),
  });

  return {
    url: accountLink.url,
    expiresAt,
  };
}

// ============================================================
// ACCOUNT STATUS CHECK
// ============================================================

/**
 * Retrieve the current status of a seller's Stripe Connect account.
 *
 * Used by the seller dashboard to display the current onboarding state
 * (e.g. "Verification pending", "Ready to receive payouts", "Action required").
 *
 * @param stripeAccountId - the seller's Stripe Connect account ID
 * @returns the account status (charges_enabled, payouts_enabled, requirements)
 */
export async function getAccountStatus(
  stripeAccountId: string
): Promise<ConnectAccountStatus> {
  const traceId = `connect_status_${stripeAccountId}_${Date.now()}`;
  const stripe = getStripe();

  PaymentLogger.info(traceId, 'connect_status_check', `Retrieving account status for ${stripeAccountId}`, {
    stripeAccountId,
  });

  const account = await stripe.accounts.retrieve(stripeAccountId);

  // Stripe types mark `requirements` as possibly undefined for some account types.
  // We default to empty values if not present.
  const req = account.requirements ?? {
    currently_due: [],
    eventually_due: [],
    past_due: [],
    disabled_reason: null,
  };

  return {
    stripeAccountId: account.id,
    stripeConnected: account.charges_enabled && account.payouts_enabled,
    chargesEnabled: account.charges_enabled,
    payoutsEnabled: account.payouts_enabled,
    detailsSubmitted: account.details_submitted,
    requirements: {
      currentlyDue: req.currently_due ?? [],
      eventuallyDue: req.eventually_due ?? [],
      pastDue: req.past_due ?? [],
      disabledReason: req.disabled_reason ?? null,
    },
  };
}

// ============================================================
// ACCOUNT.UPDATED WEBHOOK HANDLER
// ============================================================

/**
 * Handle the `account.updated` Stripe webhook event.
 *
 * This fires when Stripe updates a seller's Connect account status —
 * e.g. after they complete onboarding, after verification succeeds/fails,
 * after a payout fails, etc.
 *
 * The handler syncs the new status back to the `profiles` table so the
 * seller dashboard reflects the current state without re-querying Stripe.
 *
 * @param account - the Stripe Account object from the webhook event
 * @param traceId - trace ID for logging
 */
export async function handleAccountUpdated(
  account: Stripe.Account,
  traceId: string
): Promise<void> {
  const admin = getSupabaseAdmin();
  const stripeAccountId = account.id;
  const sellerId = (account.metadata?.sellerId as string) ?? '';

  if (!sellerId) {
    PaymentLogger.warn(traceId, 'connect_account_updated_no_seller', `account.updated event for ${stripeAccountId} has no sellerId in metadata — cannot sync`, {
      stripeAccountId,
    });
    return;
  }

  const stripeConnected = account.charges_enabled && account.payouts_enabled;

  // Stripe types mark `requirements` as possibly undefined — use safe access.
  const req = account.requirements ?? {
    currently_due: [] as string[],
    eventually_due: [] as string[],
    past_due: [] as string[],
    disabled_reason: null as string | null,
  };
  const disabledReason = req.disabled_reason ?? '';
  const pastDue = req.past_due ?? [];

  PaymentLogger.info(traceId, 'connect_account_updated', `Syncing account status for ${stripeAccountId} (seller ${sellerId}): charges=${account.charges_enabled}, payouts=${account.payouts_enabled}`, {
    sellerId,
    stripeAccountId,
    chargesEnabled: account.charges_enabled,
    payoutsEnabled: account.payouts_enabled,
    detailsSubmitted: account.details_submitted,
    disabledReason,
  });

  // Sync to the seller's profile
  const { error } = await (admin
    .from('profiles') as any)
    .update({
      stripe_connected: stripeConnected,
      // We do NOT update stripe_account_id here — it's already set when
      // the account was created. Only update the connection status.
    })
    .eq('id', sellerId);

  if (error) {
    PaymentLogger.error(traceId, 'connect_account_sync_failed', new Error(`Failed to sync account status for seller ${sellerId}: ${error.message}`), {
      sellerId,
      stripeAccountId,
      dbError: error.message,
    });
    // Don't rethrow — webhook handler should still return 200 to Stripe
    // so Stripe doesn't retry indefinitely. The next account.updated event
    // will retry the sync.
    return;
  }

  // If there are past_due requirements, the seller needs to take action.
  // Record an audit log entry so we can follow up.
  if (pastDue.length > 0) {
    PaymentLogger.warn(traceId, 'connect_account_past_due', `Seller ${sellerId} has past-due requirements: ${pastDue.join(', ')}`, {
      sellerId,
      stripeAccountId,
      pastDueCount: pastDue.length,
    });

    // TODO: enqueue an email notification to the seller asking them to
    // complete their Stripe Connect setup. (Requires P0-6 email system
    // to be live-verified.)
  }

  PaymentLogger.info(traceId, 'connect_account_synced', `Account status synced for seller ${sellerId}`, {
    sellerId,
    stripeConnected,
  });
}

// ============================================================
// HELPER: GET OR CREATE CONNECT ACCOUNT
// ============================================================

/**
 * Convenience function: get the seller's Stripe Connect account ID,
 * creating one if it doesn't exist.
 *
 * This is the entry point for the seller settings page "Connect Stripe"
 * button — it returns the account ID + onboarding URL in one call.
 *
 * @param sellerId - the seller's user ID
 * @param sellerEmail - the seller's email
 * @param sellerName - the seller's name or store name
 * @returns the account ID + onboarding URL (or null if already onboarded)
 */
export async function getOrCreateConnectAccount(
  sellerId: string,
  sellerEmail: string,
  sellerName: string
): Promise<{ accountId: string; onboardingUrl: string | null; status: ConnectAccountStatus | null }> {
  const traceId = `connect_get_or_create_${sellerId}_${Date.now()}`;

  try {
    // Step 1: Create or get the account ID
    const accountId = await createConnectAccount(sellerId, sellerEmail, sellerName);

    // Step 2: Check the current status
    const status = await getAccountStatus(accountId);

    // Step 3: If not fully onboarded, generate an onboarding URL
    if (!status.detailsSubmitted || !status.payoutsEnabled) {
      const link = await createAccountLink(accountId, sellerId);
      return {
        accountId,
        onboardingUrl: link.url,
        status,
      };
    }

    return {
      accountId,
      onboardingUrl: null,
      status,
    };
  } catch (error) {
    PaymentLogger.error(
      traceId,
      'connect_get_or_create_failed',
      error instanceof Error ? error : new Error(getErrorMessage(error)),
      { sellerId, error: getErrorMessage(error) }
    );
    throw error;
  }
}
